### ISSUE TITLE
Game Reservation Form

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/Boardwalk#8]
**User Story:**

As a Regular Customer, I want to reserve games, so I can play the games I want when I am there.

**Acceptance Criteria**

- [x] The website contains a game reservation form.
- [ ] The reservation form is placed in the footer on every page, so that users can easily find it

**Tasks**

- [ ] Integrate the reservation form into the website footer.
