### ISSUE TITLE
Selected board games displayed on a separate Game Library page

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/Boardwalk#9]
**User Story:**

As a Regular Customer, I want to view new and classic games, so I can add variety to my gameplay.

**Acceptance Criteria**

- [x] The website contains a page listing 4 new games and 4 classic games.
- [x] The page is separate from the front page and linked in the nav bar so that users can easily find it.

**Tasks**

- [x] Integrate game cards with images, name and game details into the website.
